### ISSUE TITLE
Component not working properly in Angular 13.

### ISSUE THREAD

**Issue by krooswijk** [felixthiele/radar-element#10] opened 2022-07-28 23:04 UTC
Great component. All seems to work until Angular v12. In v13 the arguments do not seem to be updated correctly. Whereas the diameter seems to be set correctly, the rings, sections and entries do not. As a result the SVG is not populated.

When `firstUpdated(_changedProperties)` is triggered the `_changedProperties` are all `undefined` instead of populated with corresponding values from Angular class.

**Comment by krooswijk** [comment] 2022-07-30 12:27
My conclusion was too fast. After some cleanup, version alignments and local module testing, the issue seems to be more specific. Probably in 12 the issue was already also present but obfuscated due to some older cached libraries. Thing now is, when using the `radar-element` directly in de AppComponent all is working fine, but when using it e.g. inside a page component loaded via a route (and router-outlet), the radar-element is present and the SVG file also, but not the grid and entries are not drawn in the SVG due to the empty sections, rings and entries. I have a small demo app with one radar outside the `router-outlet` and one loaded inside via the routed component, where the latter is not renderer and the first one is.

**Comment by felixthiele** [comment] 2022-09-24 09:54
Hey @krooswijk, somehow my notifications got messed up and I just now saw your issue. Do you have the example app code   hosted somewhere, so I could check it out? :)

**Comment by felixthiele** [comment] 2023-01-29 09:07
Since I cannot reproduce the issue and have reworked the update process (and moved from litElement to lit) I am closing this issue...

**Closed as not planned by felixthiele** 2023-01-29 09:07 UTC
